@port = 3000
@host = http://localhost:{{port}}

GET {{host}}/api/todo
content-type: application/json

###
GET {{host}}/api/todo?filter=a


###
POST {{host}}/api/todo
content-type: application/json

{
    "title": "abcd hello"
}

###
GET {{host}}/api/todo/68

###
DELETE {{host}}/api/todo/68

###
PATCH {{host}}/api/todo/68

{
    "title": "aaa 333"
}

###
PATCH {{host}}/api/todo/68

{
    "isDone": true
}

###
PATCH {{host}}/api/todo/63

{
    "title": "aaa 333 xyz",
    "isDone": true
}